#!/bin/bash
set -e

: "${GDRCD_DB_HOST:=db}"
: "${GDRCD_DB_NAME:=gdrcd}"
: "${GDRCD_DB_USER:=gdrcd}"
: "${GDRCD_DB_PASSWORD:=gdrcd}"

OVERRIDE_FILE="/var/www/html/includes/config-overrides.php"

cat > "$OVERRIDE_FILE" <<PHP
<?php
// Generated by Docker entrypoint - do not edit by hand.
\$PARAMETERS['database']['url']           = getenv('GDRCD_DB_HOST')     ?: '${GDRCD_DB_HOST}';
\$PARAMETERS['database']['username']      = getenv('GDRCD_DB_USER')     ?: '${GDRCD_DB_USER}';
\$PARAMETERS['database']['password']      = getenv('GDRCD_DB_PASSWORD') ?: '${GDRCD_DB_PASSWORD}';
\$PARAMETERS['database']['database_name'] = getenv('GDRCD_DB_NAME')     ?: '${GDRCD_DB_NAME}';
PHP

chown www-data:www-data "$OVERRIDE_FILE"

if [ ! -d /var/www/html/giocate ]; then
    mkdir -p /var/www/html/giocate
fi
chown -R www-data:www-data /var/www/html/giocate /var/www/html/imgs

if [ -n "${GDRCD_DB_HOST}" ]; then
    echo "Waiting for database at ${GDRCD_DB_HOST}:3306..."
    for i in $(seq 1 60); do
        if php -r "exit(@(new mysqli(getenv('GDRCD_DB_HOST'), getenv('GDRCD_DB_USER'), getenv('GDRCD_DB_PASSWORD'), getenv('GDRCD_DB_NAME')))->connect_errno ? 1 : 0);" 2>/dev/null; then
            echo "Database is up."
            break
        fi
        sleep 2
    done
fi

exec "$@"
